### ISSUE TITLE
Failed to parse NetParameter file: yolov2-tiny-voc.weights

### ISSUE THREAD

**Issue by eddylai** [Aleksey3ltt/WebCamYoloCuda#1]
seems weights file not inclueded

Emgu.CV.Util.CvException
  HResult=0x80131500
  Message=OpenCV: Failed to parse NetParameter file: D:\Repos\WebCamYoloCuda\bin\Debug\net6.0-windows\networks\yolov2-tiny-voc\yolov2-tiny-voc.weights
  Source=Emgu.CV
  StackTrace:
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.Dnn.DnnInvoke.cveReadNetFromDarknet(IntPtr cfgFile, IntPtr darknetModel)
   at Emgu.CV.Dnn.DnnInvoke.ReadNetFromDarknet(String cfgFile, String darknetModel)
   at WebCamYoloCuda.Form1.Load_CNN_Model() in D:\Repos\WebCamYoloCuda\Form1.cs:line 201
   at WebCamYoloCuda.Form1.button1_Click(Object sender, EventArgs e) in D:\Repos\WebCamYoloCuda\Form1.cs:line 190
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Aleksey3ltt** [comment]
Sorry, friend!
I couldn't upload the file "yolov2-tiny-voc.weights" due to the volume being exceeded.

For weights file : wget https://pjreddie.com/media/files/yolov2-tiny.weights
Rename to "yolov2-tiny-voc.weights"
